USE adlister_db;

DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(200) NOT NULL,
  email  VARCHAR(200) NOT NULL,
  password VARCHAR(150) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (email)
);

DROP TABLE IF EXISTS ads;

CREATE TABLE ads (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  title  VARCHAR(200) NOT NULL,
  description VARCHAR(500) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id)
);

SHOW TABLES;

DESCRIBE ads;
DESCRIBE users;